version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: pessoadb
    ports:
      - "5432:5432"
    volumes:
      - posgres_data:/var/lib/postgresql/data
volumes:
  posgres_data: